# Generated by Django 5.1.4 on 2024-12-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_uploadedimage_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
